// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mini.UserService.Data;

#nullable disable

namespace Mini.UserService.Data.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    partial class ServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mini.UserService.Data.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TenantId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("8f14e45f-ceea-467e-bd42-05d1a4a6b3f0"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phase 3's first tenant. Has local users and file-configured external providers.",
                            IsActive = true,
                            Key = "acme",
                            Name = "Acme Corporation"
                        },
                        new
                        {
                            TenantId = new Guid("c9f0f895-fb98-4d75-8d81-7d7c7f4a6b1e"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phase 3's second tenant. Local users only, no external providers.",
                            IsActive = true,
                            Key = "globex",
                            Name = "Globex Corporation"
                        },
                        new
                        {
                            TenantId = new Guid("a3f5b2c1-9d84-4e17-b6a0-2c8e5f1d7b93"),
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phase 9's tenant. No local user and no file-configured provider — a database-backed provider is its only way in.",
                            IsActive = true,
                            Key = "initech",
                            Name = "Initech"
                        });
                });

            modelBuilder.Entity("Mini.UserService.Data.UserIdentityRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("UserId");

                    b.ToTable("UserIdentityRoles");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            Role = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
