// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mini.UserService.Connectors.Data;

#nullable disable

namespace Mini.UserService.Connectors.Data.Migrations
{
    [DbContext(typeof(CascadingConnectorDbContext))]
    [Migration("20260908191124_InitialConnectorSchema")]
    partial class InitialConnectorSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mini.UserService.Connectors.Data.ClaimConnectorConfiguration", b =>
                {
                    b.Property<int>("ClaimConnectorConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimConnectorConfigurationId"));

                    b.Property<string>("ClaimName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("HandlerId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClaimConnectorConfigurationId");

                    b.HasIndex("HandlerId");

                    b.HasIndex("TenantId", "HandlerId")
                        .IsUnique();

                    b.ToTable("ClaimConnectorConfigurations");

                    b.HasData(
                        new
                        {
                            ClaimConnectorConfigurationId = 1,
                            ClaimName = "role",
                            HandlerId = 1,
                            TenantId = new Guid("8f14e45f-ceea-467e-bd42-05d1a4a6b3f0")
                        },
                        new
                        {
                            ClaimConnectorConfigurationId = 2,
                            ClaimName = "role",
                            HandlerId = 1,
                            TenantId = new Guid("a3f5b2c1-9d84-4e17-b6a0-2c8e5f1d7b93")
                        });
                });

            modelBuilder.Entity("Mini.UserService.Connectors.Data.Connector", b =>
                {
                    b.Property<int>("ConnectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConnectorId"));

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ConnectorId");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Connectors");

                    b.HasData(
                        new
                        {
                            ConnectorId = 1,
                            Type = 1
                        },
                        new
                        {
                            ConnectorId = 2,
                            Type = 2
                        },
                        new
                        {
                            ConnectorId = 3,
                            Type = 3
                        });
                });

            modelBuilder.Entity("Mini.UserService.Connectors.Data.ConnectorHandler", b =>
                {
                    b.Property<int>("ConnectorHandlerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConnectorHandlerId"));

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<int>("HandlerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("ConnectorHandlerId");

                    b.HasIndex("HandlerId");

                    b.HasIndex("ConnectorId", "HandlerId")
                        .IsUnique();

                    b.ToTable("ConnectorHandlers");

                    b.HasData(
                        new
                        {
                            ConnectorHandlerId = 1,
                            ConnectorId = 1,
                            HandlerId = 1,
                            IsEnabled = true
                        },
                        new
                        {
                            ConnectorHandlerId = 2,
                            ConnectorId = 3,
                            HandlerId = 1,
                            IsEnabled = true
                        },
                        new
                        {
                            ConnectorHandlerId = 3,
                            ConnectorId = 1,
                            HandlerId = 2,
                            IsEnabled = true
                        },
                        new
                        {
                            ConnectorHandlerId = 4,
                            ConnectorId = 2,
                            HandlerId = 1,
                            IsEnabled = false
                        });
                });

            modelBuilder.Entity("Mini.UserService.Connectors.Data.ConnectorHandlerCascadingTenant", b =>
                {
                    b.Property<int>("ConnectorHandlerCascadingTenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConnectorHandlerCascadingTenantId"));

                    b.Property<int>("ConnectorHandlerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<byte>("Order")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConnectorHandlerCascadingTenantId");

                    b.HasIndex("ConnectorHandlerId");

                    b.HasIndex("TenantId", "ConnectorHandlerId")
                        .IsUnique();

                    b.ToTable("ConnectorHandlerCascadingTenants");

                    b.HasData(
                        new
                        {
                            ConnectorHandlerCascadingTenantId = 1,
                            ConnectorHandlerId = 1,
                            IsEnabled = true,
                            Order = (byte)1,
                            TenantId = new Guid("8f14e45f-ceea-467e-bd42-05d1a4a6b3f0")
                        },
                        new
                        {
                            ConnectorHandlerCascadingTenantId = 2,
                            ConnectorHandlerId = 2,
                            IsEnabled = true,
                            Order = (byte)2,
                            TenantId = new Guid("8f14e45f-ceea-467e-bd42-05d1a4a6b3f0")
                        },
                        new
                        {
                            ConnectorHandlerCascadingTenantId = 3,
                            ConnectorHandlerId = 1,
                            IsEnabled = true,
                            Order = (byte)1,
                            TenantId = new Guid("a3f5b2c1-9d84-4e17-b6a0-2c8e5f1d7b93")
                        },
                        new
                        {
                            ConnectorHandlerCascadingTenantId = 4,
                            ConnectorHandlerId = 2,
                            IsEnabled = true,
                            Order = (byte)2,
                            TenantId = new Guid("a3f5b2c1-9d84-4e17-b6a0-2c8e5f1d7b93")
                        });
                });

            modelBuilder.Entity("Mini.UserService.Connectors.Data.ConnectorHandlerTenant", b =>
                {
                    b.Property<int>("ConnectorHandlerTenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConnectorHandlerTenantId"));

                    b.Property<int>("ConnectorHandlerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConnectorHandlerTenantId");

                    b.HasIndex("ConnectorHandlerId");

                    b.HasIndex("TenantId", "ConnectorHandlerId")
                        .IsUnique();

                    b.ToTable("ConnectorHandlerTenants");

                    b.HasData(
                        new
                        {
                            ConnectorHandlerTenantId = 1,
                            ConnectorHandlerId = 4,
                            IsEnabled = true,
                            TenantId = new Guid("c9f0f895-fb98-4d75-8d81-7d7c7f4a6b1e")
                        },
                        new
                        {
                            ConnectorHandlerTenantId = 2,
                            ConnectorHandlerId = 3,
                            IsEnabled = true,
                            TenantId = new Guid("8f14e45f-ceea-467e-bd42-05d1a4a6b3f0")
                        },
                        new
                        {
                            ConnectorHandlerTenantId = 3,
                            ConnectorHandlerId = 3,
                            IsEnabled = true,
                            TenantId = new Guid("a3f5b2c1-9d84-4e17-b6a0-2c8e5f1d7b93")
                        });
                });

            modelBuilder.Entity("Mini.UserService.Connectors.Data.Handler", b =>
                {
                    b.Property<int>("HandlerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HandlerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("HandlerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Handlers");

                    b.HasData(
                        new
                        {
                            HandlerId = 1,
                            Name = "GetUserRole"
                        },
                        new
                        {
                            HandlerId = 2,
                            Name = "GetUserByEmail"
                        });
                });

            modelBuilder.Entity("Mini.UserService.Connectors.Data.WebApiConnectorConfiguration", b =>
                {
                    b.Property<int>("WebApiConnectorConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WebApiConnectorConfigurationId"));

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WebApiConnectorConfigurationId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("WebApiConnectorConfigurations");

                    b.HasData(
                        new
                        {
                            WebApiConnectorConfigurationId = 1,
                            Host = "https://localhost:5014",
                            TenantId = new Guid("8f14e45f-ceea-467e-bd42-05d1a4a6b3f0")
                        },
                        new
                        {
                            WebApiConnectorConfigurationId = 2,
                            Host = "https://localhost:5014",
                            TenantId = new Guid("a3f5b2c1-9d84-4e17-b6a0-2c8e5f1d7b93")
                        });
                });

            modelBuilder.Entity("Mini.UserService.Connectors.Data.WebApiConnectorConfigurationRoute", b =>
                {
                    b.Property<int>("WebApiConnectorConfigurationRouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WebApiConnectorConfigurationRouteId"));

                    b.Property<int>("HandlerId")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("WebApiConnectorConfigurationId")
                        .HasColumnType("int");

                    b.HasKey("WebApiConnectorConfigurationRouteId");

                    b.HasIndex("HandlerId");

                    b.HasIndex("WebApiConnectorConfigurationId", "HandlerId")
                        .IsUnique();

                    b.ToTable("WebApiConnectorConfigurationRoutes");

                    b.HasData(
                        new
                        {
                            WebApiConnectorConfigurationRouteId = 1,
                            HandlerId = 1,
                            Route = "users/{id}",
                            WebApiConnectorConfigurationId = 1
                        },
                        new
                        {
                            WebApiConnectorConfigurationRouteId = 2,
                            HandlerId = 2,
                            Route = "users/by-email/{email}",
                            WebApiConnectorConfigurationId = 1
                        },
                        new
                        {
                            WebApiConnectorConfigurationRouteId = 3,
                            HandlerId = 1,
                            Route = "users/{id}",
                            WebApiConnectorConfigurationId = 2
                        },
                        new
                        {
                            WebApiConnectorConfigurationRouteId = 4,
                            HandlerId = 2,
                            Route = "users/by-email/{email}",
                            WebApiConnectorConfigurationId = 2
                        });
                });

            modelBuilder.Entity("Mini.UserService.Connectors.Data.ClaimConnectorConfiguration", b =>
                {
                    b.HasOne("Mini.UserService.Connectors.Data.Handler", "Handler")
                        .WithMany()
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Handler");
                });

            modelBuilder.Entity("Mini.UserService.Connectors.Data.ConnectorHandler", b =>
                {
                    b.HasOne("Mini.UserService.Connectors.Data.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mini.UserService.Connectors.Data.Handler", "Handler")
                        .WithMany()
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connector");

                    b.Navigation("Handler");
                });

            modelBuilder.Entity("Mini.UserService.Connectors.Data.ConnectorHandlerCascadingTenant", b =>
                {
                    b.HasOne("Mini.UserService.Connectors.Data.ConnectorHandler", "ConnectorHandler")
                        .WithMany()
                        .HasForeignKey("ConnectorHandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectorHandler");
                });

            modelBuilder.Entity("Mini.UserService.Connectors.Data.ConnectorHandlerTenant", b =>
                {
                    b.HasOne("Mini.UserService.Connectors.Data.ConnectorHandler", "ConnectorHandler")
                        .WithMany()
                        .HasForeignKey("ConnectorHandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectorHandler");
                });

            modelBuilder.Entity("Mini.UserService.Connectors.Data.WebApiConnectorConfigurationRoute", b =>
                {
                    b.HasOne("Mini.UserService.Connectors.Data.Handler", "Handler")
                        .WithMany()
                        .HasForeignKey("HandlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mini.UserService.Connectors.Data.WebApiConnectorConfiguration", "WebApiConnectorConfiguration")
                        .WithMany("Routes")
                        .HasForeignKey("WebApiConnectorConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Handler");

                    b.Navigation("WebApiConnectorConfiguration");
                });

            modelBuilder.Entity("Mini.UserService.Connectors.Data.WebApiConnectorConfiguration", b =>
                {
                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
